on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ikuoshige/mkdocs_docker:insider
    steps:
      - uses: actions/checkout@v2
      - name: build and deploy
      - run: |
          bash build.sh
          mkdocs gh-deploy --force
