on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-versiuon: 3.9
      # GitHubシークレットからパスワードファイルを取得
      - name: Get password file from secret
        env:
          PASSWORD_FILE: ${{ secrets.PASSWORDS }}
        run: |
          # パスワードファイルを作業ディレクトリにコピー
          echo "$PASSWORD_FILE" > passwords.yml

      - run: pip install mkdocs-material=="9.*" mkdocs-macros-plugin mkdocs-glightbox mkdocs-static-i18n mkdocs-encryptcontent-plugin
      - run: mkdocs build -f mkdocs_blog.yml &&
             mkdocs gh-deploy -d site/
      # ワークフローの最後にパスワードファイルを削除
      - name: Clean up
        run: rm passwords.yml
